### PR TITLE
Add contentState to SimpleDecorator.prototype.getDecorations

### PR DESCRIPTION
**Pull request by iantanwx**
In keeping with API changes in v0.10.0

Please see https://facebook.github.io/draft-js/docs/v0-10-api-migration.html#content

### CODE REVIEW

**Comment by Soreine** [comment]
Thank you!

**Comment by Soreine** [comment]
I haven't checked if the README examples are still valid. Does it need to be updated too?

**Comment by iantanwx** [comment]
Whoops, looks like I forgot about the README. I see that you've updated it; thanks for the quick response. It doesn't make a big difference I think, but if you do not make use of `contentState` to find the entity, Draft.js start spitting out an insane amount of warnings.

**Comment by Soreine** [comment]
> Draft.js start spitting out an insane amount of warnings

Gross... haha. I'll publish a new version of the plugin.

**Pull request merged**
